### ISSUE TITLE
Cambiar css's

### ISSUE THREAD

**Issue by Octlopez04** [Octlopez04/octlopez04.github.io#2]
Hay que cambiar css por tipo de contenedor 
Ej; un css para el header y ponerlo en los que se pueda y si no copiar y modificar en uno exclusivo, ya si quieren al final lo volcamos todo en uno solo.
Para hacernos la vida mas facil al programar un chingo
@sigala0315 
@enmai9 

![FB_IMG_1664592890478.jpg](https://user-images.githubusercontent.com/114187056/194600177-931aee6c-7d11-4451-b889-1f13f998bac4.jpg)

**Comment by enmai9** [comment]
pvto

**Comment by Octlopez04** [comment]
Ya qwuedo sin uso se tomaron otras medidas
